export const AddEditMapProductTemplateColumns = [
    {
        Header: "Select",
        id: "selection"
    },
    // {
    //     Header: "Product ID",
    //     accessor: "productId",
    //     disableFilters: true,
    //     id: 'productId'
    // },
    {
        Header: "Product Name",
        accessor: "productName",
        disableFilters: true,
        id: 'productName'
    },
    {
        Header: "Product Type",
        accessor: "productTypeDescription.description",
        disableFilters: true,
        id: 'productType'
    },
    {
        Header: "Service Type",
        accessor: "serviceTypeDescription.description",
        disableFilters: true,
        id: 'serviceType'
    }, 
    {
        Header: "Recurring Charge",
        accessor: "rcAmount",
        disableFilters: true,
        id: 'rcAmount'
    },
    {
        Header: "Non Recurring Charge",
        accessor: "nrcAmount",
        disableFilters: true,
        id: 'nrcAmount'
    },  
    // {
    //     Header: "Status",
    //     accessor: "statusDesc.description",
    //     disableFilters: true,
    //     id: 'currStatus'
    // },
    // {
    //     Header: "Created By",
    //     accessor: "createdByName.firstName",
    //     disableFilters: true,
    //     id: 'createdBy'
    // }
   
    // {
    //     Header: "View Workflow Template"
    // }
]

export const SelectConfirmProductMappingTemplateColumns = [
    {
        Header: "Select",
        id: "selection"
    },
    // {
    //     Header: "Mapping ID",
    //     accessor: "mappingId",
    //     disableFilters: true,
    //     id: 'mappingId'
    // },
    {
        Header: "Product Name",
        accessor: "productName",
        disableFilters: true,
        id: 'productName'
    },
    // {
    //     Header: "Generate Date",
    //     accessor: "createdAt",
    //     disableFilters: true,
    //     id: 'createdAt'
    // },
    // {
    //     Header: "Generated by",
    //     accessor: "createdByName.firstName",
    //     disableFilters: true,
    //     id: 'createdBy'
    // },    
    {
        Header: "Product Type",
        accessor: "productTypeDescription.description",
        disableFilters: true,
        id: 'productType'
    },
    {
        Header: "Service Type",
        accessor: "serviceTypeDescription.description",
        disableFilters: true,
        id: 'serviceType'
    },
    {
        Header: "Use Current Charge",
        accessor: "useExistingCharge",
        disableFilters: true,
        id: 'useExistingCharge'
    },     
    {
        Header: "Use New Charge",
        accessor: "useNewCharge",
        disableFilters: true,
        id: 'useNewCharge'
    },
    {
        Header: "Create New Charge",
        accessor: "createNewCharge",
        disableFilters: true,
        id: 'createNewCharge'
    },
    {
        Header: "Current Recurring Charge",
        accessor: "rcAmount",
        disableFilters: true,
        id: 'rcAmount'
    },
    {
        Header: "Current Non Recurring Charge",
        accessor: "nrcAmount",
        disableFilters: true,
        id: 'nrcAmount'
    },
    {
        Header: "New Recurring Charge",
        accessor: "newRcAmount",
        disableFilters: true,
        id: 'newRcAmount'
    },
    {
        Header: "New Non Recurring Charge",
        accessor: "newNrcAmount",
        disableFilters: true,
        id: 'newNrcAmount'
    },
    {
        Header: "New Charges Added",
        accessor: "addedCharges",
        disableFilters: true,
        id: 'addedCharges'
    },
    {
        Header: "Use Current Term",
        accessor: "useExistingTerm",
        disableFilters: true,
        id: 'useExistingTerm'
    },
    {
        Header: "Use New Term",
        accessor: "useNewTerm",
        disableFilters: true,
        id: 'useNewTerm'
    },
    {
        Header: "Create New Term",
        accessor: "createNewTerm",
        disableFilters: true,
        id: 'createNewTerm'
    },
    // {
    //     Header: "Template ID",
    //     accessor: "workflowId",
    //     disableFilters: true,
    //     id: 'workflowId'
    // }
]

export const ConfirmProductMappingTemplateColumnsPromo = [
    {
        Header: "Select",
        id: "selection"
    }, 
    {
        Header: "Product Name",
        accessor: "productName",
        disableFilters: true,
        id: 'productName'
    },  
    {
        Header: "Product Type",
        accessor: "productTypeDescription.description",
        disableFilters: true,
        id: 'productType'
    },
    {
        Header: "Service Type",
        accessor: "serviceTypeDescription.description",
        disableFilters: true,
        id: 'serviceType'
    },
    // {
    //     Header: "Use Current Charge",
    //     accessor: "useExistingCharge",
    //     disableFilters: true,
    //     id: 'useExistingCharge'
    // },     
    // {
    //     Header: "Use New Charge",
    //     accessor: "useNewCharge",
    //     disableFilters: true,
    //     id: 'useNewCharge'
    // },   
    {
        Header: "Current Recurring Charge",
        accessor: "rcAmount",
        disableFilters: true,
        id: 'rcAmount'
    },
    {
        Header: "Current Non Recurring Charge",
        accessor: "nrcAmount",
        disableFilters: true,
        id: 'nrcAmount'
    },
    // {
    //     Header: "New Recurring Charge",
    //     accessor: "newRcAmount",
    //     disableFilters: true,
    //     id: 'newRcAmount'
    // },
    // {
    //     Header: "New Non Recurring Charge",
    //     accessor: "newNrcAmount",
    //     disableFilters: true,
    //     id: 'newNrcAmount'
    // },    
    {
        Header: "Use Current Term",
        accessor: "useExistingTerm",
        disableFilters: true,
        id: 'useExistingTerm'
    },
    {
        Header: "Use New Term",
        accessor: "useNewTerm",
        disableFilters: true,
        id: 'useNewTerm'
    },   
    // {
    //     Header: "Template ID",
    //     accessor: "workflowId",
    //     disableFilters: true,
    //     id: 'workflowId'
    // }
]


export const MappedWorkflowListColumns = [
    {
        Header: "Select"
    },
    {
        Header: "Action"
    },
    {
        Header: "Product ID",
        accessor: "productId",
        disableFilters: true,
        id: 'productId'
    },
    {
        Header: "Product Name",
        accessor: "productName",
        disableFilters: true,
        id: 'productName'
    },
    {
        Header: "Product Type",
        accessor: "productType",
        disableFilters: true,
        id: 'productType'
    },
    {
        Header: "Created Date",
        accessor: "createdAt",
        disableFilters: true,
        id: 'createdAt'
    },
    {
        Header: "Created By",
        accessor: "createdBy",
        disableFilters: true,
        id: 'createdBy'
    },    
    {
        Header: "Service Type",
        accessor: "mapping.serviceTypeDescription",
        disableFilters: true,
        id: 'serviceType'
    },   
   
]