export const SubmitInvoiceColumnList = [
    {
        Header: "Generate Id",
        accessor: "processId",
        disableFilters: true
    },
    {
        Header: "Generate Date",
        accessor: "updatedAt",
        disableFilters: true
    },
    {
        Header: "Generated By",
        accessor: "createdByName.firstName",
        disableFilters: true
    },
    // {
    //     Header: "Invoice Period",
    //     accessor: "invoiceStartDate",
    //     disableFilters: true
    // },
    {
        Header: "Total Invoice Processed",
        accessor: "totalProcessed",
        disableFilters: true
    },
    {
        Header: "Total Success",
        accessor: "successCount",
        disableFilters: true
    },
    {
        Header: "Total Failed",
        accessor: "failureCount",
        disableFilters: true
    },
    // {
    //     Header: "Log Location",
    //     accessor: "logLocation",
    //     disableFilters: true
    // },
    // {
    //     Header: "PDF Location",
    //     accessor: "pdfLocation",
    //     disableFilters: true
    // },
    // {
    //     Header: "Report",
    //     accessor: "report",
    //     disableFilters: true
    // }
]