export const GenerateInvoiceColumnList = [
    {
        Header: "Process Id",
        accessor: "processId",
        disableFilters: true
    },
    {
        Header: "Generated By",
        accessor: "createdByName.firstName",
        disableFilters: true
    },
    // {
    //     Header: "Invoice Period",
    //     accessor: "invoiceStartDate",
    //     disableFilters: true
    // },
    {
        Header: "Process Date",
        accessor: "processDate",
        disableFilters: true
    },
    {
        Header: "Total Processed",
        accessor: "totalProcessed",
        disableFilters: true
    },
    {
        Header: "Success",
        accessor: "successCount",
        disableFilters: true
    },
    {
        Header: "Failed",
        accessor: "failureCount",
        disableFilters: true
    },
    {
        Header: "Invoice Status",
        accessor: "invoices[0].invoiceStatus",
        disableFilters: true
    },
    {
        Header: "Billing Status",
        accessor: "invoices[0].billingStatus",
        disableFilters: true
    },
    /*{
        Header: "Regenerated Count",
        accessor: "invoiceRegenCnt",
        disableFilters: true
    },*/
    // {
    //     Header: "Log Location",
    //     accessor: "pdfLocation",
    //     disableFilters: true
    // },
    // {
    //     Header: "Report",
    //     accessor: "report",
    //     disableFilters: true
    // }
]