
import { computeDynamicBaseURL } from "./common/util/util";
const dynamicBase = computeDynamicBaseURL();

export const properties = {
  API_ENDPOINT: process.env.REACT_APP_API_ENDPOINT,
  //API_ENDPOINT: 'https://dtworks-test.comquest-brunei.com:1443/base',
  API_ENDPOINT_SOCKET: process.env.REACT_APP_API_ENDPOINT_SOCKET,
  CHAT_SOCKET_ENDPOINT: process.env.REACT_APP_CHAT_SOCKET_ENDPOINT,
  API_SERVICE_PORT: process.env.REACT_APP_SERVICE_PORT,
  SOCKET_PATH: process.env.REACT_APP_SOCKET_PATH,
  // STAGE
  // REACT_APP_TENANT_ID: '7106ddef-ead3-420d-85ae-cd26eda09350', // HS,
  // REACT_APP_TENANT_ID: '6ae3db06-dd13-44e0-b45b-66eab2bb25e2', // PS,
  // REACT_APP_TENANT_ID: 'd69b0543-5e19-4345-95d5-1f1146f88442', // CS,

  // DEMO
  // REACT_APP_TENANT_ID: '887876b3-d531-40df-8bf9-88af8b10c04a', // CS EXT,
  // REACT_APP_TENANT_ID: '123198c5-ead1-475b-b3f9-082024a91d36', // HS EXT,
  // REACT_APP_TENANT_ID: '9017cd5c-7a74-4995-b7f9-ecdcf6b5d7ab', // PS EXT,
  // REACT_APP_TENANT_ID: '3d977118-f16a-4a35-bbf8-f9bc48409cb9', // CS INT,
  // REACT_APP_TENANT_ID: '274d1cef-388c-42a2-9eea-85eebf6ea131', // HS INT,
  // REACT_APP_TENANT_ID: 'c19e6215-dae0-4d65-81ad-d1a8c8401cc4', // PS INT,
  // REACT_APP_TENANT_ID: 'd5c30627-1ce7-4101-adcd-7807adc4361f', // CS SALES,
  // REACT_APP_TENANT_ID: 'e3457b9d-74ce-4207-8458-4264e516da4d', // HS SALES,
  // REACT_APP_TENANT_ID: '2ef18fab-b7ab-492f-bbfb-a56fd2008b25', // PS SALES,

  REACT_APP_TENANT_ID: process.env.REACT_APP_TENANT_ID,

  REACT_APP_BASE: dynamicBase,
  CHANNEL: {
    UAM_WEB: 'UAM_WEB',
    UAM_MOBILE: 'UAM_MOBILE'
  },
  PAGINATION: {
    LIMIT: 10
  },
  LIVESTREAMTIME: (5 * 60 * 1000),
  // LIVESTREAMTIME: (3000),
  USER_API: "/api/users",
  THEME_API: "/api/config",
  CUSTOMER_API: "/api/customer",
  ACCESS_NUMBER: "/api/accessNumber",
  BUSINESS_ENTITY_API: '/api/master/lookup',
  BUSINESS_PARAMETER_API: '/api/business-parameter',
  ADDRESS_LOOKUP_API: '/api/master/address-lookup',
  PRODUCT_LOOKUP_API: '/api/lookup/product-lookup',
  ORGANIZATION: '/api/organization',
  PLANS_API: '/api/plans',
  CREATE_TOPUP_API: '/api/connection/service/booster',
  CREATE_VAS_API: '/api/connection/service/vas',
  CUSTOMER360_API: '/api/customer',
  ACTIVE_BOOSTERS_API: '/api/customer/active-boosters',
  PURCHASE_HISTORY_API: '/api/customer/purchase-history',
  VAS_API: '/api/customer/vas',
  AVAILABLE_TOPUP_API: '/api/plans?plantype=TOPUP',
  ROLE_API: '/api/role',
  SERVICES_SUMMARY_API: '/api/customer/services-summary',
  ACCOUNTS_LIST_API: '/api/customer/account-id-list',
  ACCOUNT_DETAILS_API: '/api/accounts',
  SERVICES_LIST_API: '/api/customer/services-list',
  SERVICE_API: '/api/customer/service-details',
  SERVICE_API_2: '/api/service',
  SERVICE_REALTIME_API: '/api/customer/service-realtime',
  PLAN_UPGRADE_API: '/api/connection/service/upgrade',
  PLAN_DOWNGRADE_API: '/api/connection/service/downgrade',
  SERVICE_BADGE_API: '/api/customer/service-badge',
  TELEPORT_RELOCATE_API: "/api/connection/service/teleport-relocate",
  PENDING_PLANS_API: '/api/customer/pending-plans',
  ATTACHMENT_API: '/api/common/attachment',
  BAR_SERVICE: '/api/connection/service/bar',
  UNBAR_SERVICE: '/api/connection/service/unbar',
  CUSTOMER_DETAILS: '/api/customer',
  COMPLAINT_API: '/api/complaint',
  SERVICE_TYPE_COUNT: '/api/interaction/count',
  SERVICE_REQUEST_LIST_BY_CUSTOMER: '/api/service-request/list',
  SERVICE_REQUEST_DETAILS: '/api/service-request',
  ICCID_API: '/api/iccid',
  CUSTOMER_INQUIRY_API: "/api/lead",
  CUSTOMER_INQUIRY_API_2: "/api/inquiry",
  INTERACTION_API: '/api/interaction',
  CATALOGUE_API: '/api/catalog',
  CAMPAIGN_API: '/api/campaign',
  ROLE_LOOKUP_API: '/api/lookup/roles',
  USER_LOOKUP_API: '/api/lookup/users',
  LOOKUP_ITEMS: '/api/lookup/items',
  KIOSK_GET_API: '/api/kiosk/createKiosk',
  KIOSK_REF_API: '/api/kiosk',
  KIOSK_CANCEL_API: '/api/kiosk/cancelKiosk',
  CONNECTION_API: '/api/connection/service/list',
  WORKFLOW_APIEx: '/api/workflow/executeWorkFlow',
  WORKFLOW_DEFN_API: '/api/workflow',
  WORKFLOW_ASSIGN_SELF_API: '/api/workflow/assign/self',
  WORKFLOW_GET_STATE_API: '/api/workflow/state',
  WORKFLOW_HIERARCHY_API: '/api/lookup/org-hierarchy-roles',
  WORKFLOW_DBMODEL_API: '/api/lookup/db-schema-info',
  FORMS_DEFN_API: '/api/forms',
  FORMS_DATA_API: '/api/forms/form-data',
  NOTIFICATION_API: '/api/notification',
  NOTES_API: '/api/notes',
  CONNECTION_TERMINATE_API: "/api/connection/service/terminate",
  CONNECTION_TERMINATED_NUMBERS_API: "/api/connection/service/terminate-list",
  CONNECTION_TELEPORTANDRELOCATE_API: "/api/connection/service/getTeleportRelocation",
  RESOLVE_FAILED_INTERACTION_API: '/api/customer/interaction/resolve',
  CHARGE_API: '/api/charge',
  ASSET_API: '/api/assetitem',
  ASSET_API_2: '/api/assetitem',
  CATALOG_SERVICE_API: '/api/service',
  ADDON_API: '/api/addon',
  CHAT_API: '/api/chat',
  CONTRACT_API: '/api/contract',
  INVOICE_API: '/api/invoice',
  ADJUSTMENT_API: '/api/adjustment',
  BILLING_API: '/api/billing',
  CONNECTION_COUNT_API: '/api/connection/service/count',
  CONNECTION_COUNT_BY_TYPE: '/api/connection/service/connection-types-count',
  DASHBOARD_API: '/api/dashboard',
  CONNECTION_ADDON_API: '/api/connection/service/add-on',
  CONNECTION_UPGRADE_DOWNGRADE_API: '/api/connection/service/upgrade-downgrade',
  REPORTS_API: '/api/report',
  SMTP_API: '/api/smtp',
  EMAIL_TEMPLATE_API: '/api/email-template',
  HELPDESK_API: '/api/helpdesk',
  BI_API: '/api/bi',
  DEPT_USER: '/api/lookup/department-user',
  ORDERS_API: '/api/orders',
  BULK_UPLOAD_API: '/api/bulk-upload',
  QUALITY_MONITORING: '/api/quality/monitoring',
  ENTITY_LOOkUP_API: '/api/lookup/entity',
  PORTAL_SETTING_API: '/api/portal-setting',
  INTEGRATION_API: '/api/integration',
  MAINMENU_API: '/api/master/menu',
  GET_MONITORING_API: '/api/chat/monitor',
  SLA_SETTINGS_API: '/api/sla-settings',
  JOB_SERVICE_API: '/api/jobs',
  //New Routes:
  AUTH_API: '/api/auth',
  MASTER_API: '/api/master',
  KNOWLEDGE_API: '/api/knowledge-base',
  WADASHBOARD_API: '/api/whatsapp',
  PROFILE_API: '/api/profile',
  COMMON_API: '/api/common',
  PRODUCT_API: '/api/product',
  ORDER_API: '/api/order',
  INTELLIGENCE_API: '/api/intelligence-corner',
  WORKFLOW_API: '/api/workflow',
  APPOINTMENT_API: '/api/appointment',
  TEMPLATE_API: '/api/template',
  INVENTORY_API: '/api/inventory',
  LEAD_API: '/api/lead',
  EXTERNAL_API: '/api/external-api-call',
  SLA_API: '/api/sla',
  TASK_API: '/api/task',
  WRITE_OFF_API: '/api/writeoff',
  RECEIPT_API: '/api/receipt'
};
